import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { PaymentProvider } from "./payments/context/PaymentContext";
import Head from "next/head";

const ubuntu = Ubuntu({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<PaymentProvider>
			<html lang="es">
				<Head>
					<script
						async
						type="text/javascript"
						src="https://checkout.wompi.co/widget.js"
					></script>
				</Head>
				<body className={`${ubuntu.className}`}>{children}</body>
			</html>
		</PaymentProvider>
	);
}
